# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/prompt_eng_vm',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/prompt_eng_vm',
                'lib_path': 'prompt_eng_vm'},
  'syms': {'prompt_eng_vm.core': {'prompt_eng_vm.core.foo': ('core.html#foo', 'prompt_eng_vm/core.py')}}}
