# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_object_detection.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/01_object_detection.ipynb 2
from PIL import Image

# %% ../nbs/01_object_detection.ipynb 4
def foo(): pass
